export const DICE_TEMPLATES = {
    white: {
        id: 'white',
        name: 'Classic White',
        thName: 'ลูกเต๋าคลาสสิกขาว',
        rarity: 'common',
        icon: '🎲',
        bg: '#fffef8',
        border: '#3a3232',
        dot: '#3a3232',
        face1: '#ff3366',
        roughness: 0.5,
        metalness: 0.1,
        source: 'default',
        sourceTextEN: 'Unlocked by default',
        sourceTextTH: 'ปลดล็อกเริ่มต้น'
    },
    panda: {
        id: 'panda',
        name: 'Chibi Panda',
        thName: 'ลูกเต๋าแพนด้าชิบิ',
        rarity: 'common',
        icon: '🐼',
        bg: '#18181b',
        border: '#e4e4e7',
        dot: '#22c55e',
        face1: '#ef4444',
        roughness: 0.4,
        metalness: 0.1,
        source: 'chest',
        sourceTextEN: 'Found in Common Chests',
        sourceTextTH: 'พบได้ในหีบธรรมดา'
    },
    gold: {
        id: 'gold',
        name: 'Golden Dice',
        thName: 'ลูกเต๋าทองคำ',
        rarity: 'rare',
        icon: '🪙',
        bg: '#fef08a',
        border: '#b45309',
        dot: '#ca8a04',
        face1: '#ef4444',
        roughness: 0.08,
        metalness: 0.95,
        source: 'level',
        levelRequired: 3,
        sourceTextEN: 'Reach Level 3',
        sourceTextTH: 'เข้าถึงเลเวล 3'
    },
    emerald: {
        id: 'emerald',
        name: 'Emerald Dice',
        thName: 'ลูกเต๋ามรกต',
        rarity: 'rare',
        icon: '💚',
        bg: '#10b981',
        border: '#064e3b',
        dot: '#34d399',
        face1: '#fbbf24',
        roughness: 0.10,
        metalness: 0.70,
        source: 'level',
        levelRequired: 7,
        sourceTextEN: 'Reach Level 7',
        sourceTextTH: 'เข้าถึงเลเวล 7'
    },
    songkran: {
        id: 'songkran',
        name: 'Songkran Splash',
        thName: 'ลูกเต๋ามหาสงกรานต์',
        rarity: 'rare',
        icon: '💦',
        bg: '#e0f2fe',
        border: '#0284c7',
        dot: '#38bdf8',
        face1: '#ff6b8b',
        roughness: 0.02,
        metalness: 0.75,
        source: 'level',
        levelRequired: 11,
        sourceTextEN: 'Reach Level 11',
        sourceTextTH: 'เข้าถึงเลเวล 11'
    },
    floating_market: {
        id: 'floating_market',
        name: 'Floating Market',
        thName: 'ลูกเต๋าตลาดน้ำ',
        rarity: 'rare',
        icon: '🚣',
        bg: '#d97706',
        border: '#451a03',
        dot: '#f59e0b',
        face1: '#b45309',
        roughness: 0.75,
        metalness: 0.05,
        source: 'level',
        levelRequired: 16,
        sourceTextEN: 'Reach Level 16',
        sourceTextTH: 'เข้าถึงเลเวล 16'
    },
    mango: {
        id: 'mango',
        name: 'Mango Sticky Rice',
        thName: 'ลูกเต๋ามะม่วงอกร่อง',
        rarity: 'rare',
        icon: '🥭',
        bg: '#facc15',
        border: '#451a03',
        dot: '#fffbef',
        face1: '#ea580c',
        roughness: 0.3,
        metalness: 0.1,
        source: 'chest',
        sourceTextEN: 'Found in Rare Chests',
        sourceTextTH: 'พบได้ในหีบหายาก'
    },
    neontuktuk: {
        id: 'neontuktuk',
        name: 'Tuk Tuk Neon',
        thName: 'ลูกเต๋านีออนตุ๊กตุ๊ก',
        rarity: 'rare',
        icon: '🛺',
        bg: '#06b6d4',
        border: '#083344',
        dot: '#ec4899',
        face1: '#facc15',
        roughness: 0.15,
        metalness: 0.7,
        source: 'wheel',
        sourceTextEN: 'Won from Lucky Wheel',
        sourceTextTH: 'สุ่มได้จากวงล้อนำโชค'
    },
    naga: {
        id: 'naga',
        name: 'Naga Scale Dice',
        thName: 'ลูกเต๋าเกล็ดพญานาค',
        rarity: 'epic',
        icon: '🐉',
        bg: '#0f766e',
        border: '#115e59',
        dot: '#2dd4bf',
        face1: '#fbbf24',
        roughness: 0.12,
        metalness: 0.65,
        source: 'level',
        levelRequired: 22,
        sourceTextEN: 'Reach Level 22',
        sourceTextTH: 'เข้าถึงเลเวล 22'
    },
    garuda: {
        id: 'garuda',
        name: 'Garuda Crest Dice',
        thName: 'ลูกเต๋าพญาครุฑ',
        rarity: 'epic',
        icon: '🦅',
        bg: '#dc2626',
        border: '#7f1d1d',
        dot: '#facc15',
        face1: '#ffffff',
        roughness: 0.20,
        metalness: 0.70,
        source: 'level',
        levelRequired: 28,
        sourceTextEN: 'Reach Level 28',
        sourceTextTH: 'เข้าถึงเลเวล 28'
    },
    yak: {
        id: 'yak',
        name: 'Yak Guardian Dice',
        thName: 'ลูกเต๋ายักษ์ทศกัณฐ์',
        rarity: 'epic',
        icon: '👹',
        bg: '#065f46',
        border: '#064e3b',
        dot: '#fbbf24',
        face1: '#ef4444',
        roughness: 0.50,
        metalness: 0.25,
        source: 'level',
        levelRequired: 35,
        sourceTextEN: 'Reach Level 35',
        sourceTextTH: 'เข้าถึงเลเวล 35'
    },
    phayanak: {
        id: 'phayanak',
        name: 'Phaya Nak Dragon',
        thName: 'ลูกเต๋าพญานาคราช',
        rarity: 'epic',
        icon: '🔮',
        bg: '#0d9488',
        border: '#115e59',
        dot: '#fbbf24',
        face1: '#ef4444',
        roughness: 0.1,
        metalness: 0.8,
        source: 'chest',
        sourceTextEN: 'Found in Epic Chests',
        sourceTextTH: 'พบได้ในหีบอีปิค'
    },
    thaitea: {
        id: 'thaitea',
        name: 'Thai Tea Glass',
        thName: 'ลูกเต๋าแก้วชาไทย',
        rarity: 'epic',
        icon: '🥤',
        bg: '#ea580c',
        border: '#7c2d12',
        dot: '#fffef8',
        face1: '#ec4899',
        roughness: 0.05,
        metalness: 0.9,
        source: 'achievement',
        sourceTextEN: 'Sticker Album Rewards',
        sourceTextTH: 'รางวัลความสำเร็จสะสมสติกเกอร์'
    },
    temple: {
        id: 'temple',
        name: 'Temple Tile Dice',
        thName: 'ลูกเต๋ากระเบื้องวัด',
        rarity: 'legendary',
        icon: '🛕',
        bg: '#ea580c',
        border: '#7c2d12',
        dot: '#fef08a',
        face1: '#ca8a04',
        roughness: 0.15,
        metalness: 0.80,
        source: 'level',
        levelRequired: 42,
        sourceTextEN: 'Reach Level 42',
        sourceTextTH: 'เข้าถึงเลเวล 42'
    },
    lantern: {
        id: 'lantern',
        name: 'Lantern Festival',
        thName: 'ลูกเต๋าโคมยี่เป็ง',
        rarity: 'legendary',
        icon: '🏮',
        bg: '#f97316',
        border: '#7c2d12',
        dot: '#fde047',
        face1: '#dc2626',
        roughness: 0.40,
        metalness: 0.15,
        source: 'level',
        levelRequired: 48,
        sourceTextEN: 'Reach Level 48',
        sourceTextTH: 'เข้าถึงเลเวล 48'
    },
    goldtemple: {
        id: 'goldtemple',
        name: 'Golden Temple Palace',
        thName: 'ลูกเต๋าพระบรมมหาราชวัง',
        rarity: 'legendary',
        icon: '👑',
        bg: '#fbbf24',
        border: '#b45309',
        dot: '#dc2626',
        face1: '#ffffff',
        roughness: 0.02,
        metalness: 0.95,
        source: 'travel_pass',
        sourceTextEN: 'Travel Pass Level 15 Reward',
        sourceTextTH: 'รางวัลเวล 15 ทริปพาสปอร์ต'
    },
    monsoon: {
        id: 'monsoon',
        name: 'Monsoon Rainbow',
        thName: 'ลูกเต๋าสายรุ้งมรสุม',
        rarity: 'legendary',
        icon: '🌈',
        bg: '#c084fc',
        border: '#581c87',
        dot: '#38bdf8',
        face1: '#fb7185',
        roughness: 0.1,
        metalness: 0.5,
        source: 'achievement_all_boards',
        sourceTextEN: 'Unlock all 4 boards to earn',
        sourceTextTH: 'สะสมครบ 4 แผนที่รับทันที'
    }
};
